config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
    devise_scope :user do
      get 'users/sign_out' => 'devise/sessions#destroy'
    end

  # Defines the root path route ("/")
  # root "articles#index"

  root to: "users#index"
  
  resources :users , only: [:index , :show ] do
      resources :posts , only: [:index , :show , :new , :create , :destroy] do
        resources :comments , only: [:new , :create , :destroy]
        resources :likes , only: [:new , :create]
      end
  end

  
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)

    if user.present?
      if user.role == 'admin'
        
        can :destroy, Post , user_id: user.id
        can :destroy , Comment , user_id: user.id
      else
    
        can :read, Post
        can :read, Comment
  
      end
    
   end
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :destroy , Post , user_id: user.id
   
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user , foreign_key: 'user_id' , class_name: 'User'
    belongs_to :post , foreign_key: 'post_id' , class_name: 'Post'
    after_save :post_comment_counter

    def post_comment_counter
        post.increment!(:comments_counter)
    end

    def update_user_posts_comment_counter
        post = Post.find(post_id)
        post.update(comments_counter: post.comments.count)
    end
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user , foreign_key: 'user_id'
    belongs_to :post , foreign_key: 'post_id'
    after_save :post_like_counter

    def post_like_counter
        post.increment!(:likes_counter)
    end
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user , foreign_key: 'user_id' ,  class_name: 'User'
    has_many :comments , foreign_key: 'post_id'
    has_many :likes , foreign_key: 'post_id'
    after_save :user_counters

    validates :title , presence: true , length: {maximum: 250}
    validates :comments_counter, :likes_counter, presence: true,
                                               numericality: { only_integer: true, greater_than_or_equal_to: 0 }
   
    
   def user_counters
    user.increment!(:post_counter)
   end 
    
    def five_most_recent_comment
       comments.order(created_at: :asc).limit(5)
    end

    def update_user_posts_counter
        user = User.find(user_id)
        user.update(post_counter: user.posts.count)
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable 
        
    has_many :posts , foreign_key: 'user_id'
    has_many :likes 
    has_many :comments 
  
    validates :name , presence: true
    validates :post_counter , numericality: {only_integer: true, greater_than_or_equal_to: 0}
    after_initialize :init
    before_save :default_photo

    def recent_post
        posts.order(created_at: :desc).limit(3)
    end

    def init
        self.post_counter ||= 0
        true
    end

    def default_photo
        if photo.nil?
            self.photo = 'https://img.myloview.com/posters/social-media-user-icon-default-avatar-profile-image-400-251200036.jpg'
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password password_confirmation])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def new
        @comment=Comment.new
        @user = current_user
    end

    def create
        @post = Post.find(params[:post_id] || params[:id])
        @comment = Comment.new(comment_params)
        @comment.user_id = current_user.id
        @comment.post = @post

        respond_to do |format|
            if @comment.save!
              format.html do
                redirect_to user_post_url(current_user, @post), notice: 'Comment was successfully created.'
              end
            else
              format.html { render :new, status: :unprocessable_entity }
            end
          end


      
    end

    def comment_params
        params.require(:comment).permit(:text)
    end

    def destroy
      @post = Comment.find_by_id(params[:id])
      @post.destroy
      @post.update_user_posts_comment_counter
      redirect_to user_posts_path
      
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

    def new
        @like= Like.new
        @user= current_user
    end

    def create
        @post = Post.find(params[:post_id] || params[:id])
        @like=Like.new(post_id: @post.id , user_id: current_user.id)
        @like.user_id= current_user.id

        respond_to do |format|
            if @like.save
              format.html { redirect_to user_post_url(current_user, @post), notice: 'Like was successfully created.' }
            else
              format.html { render :new, status: :unprocessable_entity }
            end
          end
       
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @user=User.find(params[:user_id])

        @post= @user.posts
        @post=Post.includes(:user)
       
    end

    def show
        @user=User.find(params[:user_id])
        @post=Post.find(params[:id])
       
    end


    def new
        @post = Post.new
        @user=current_user
    end

    def create
        @post=Post.new(post_params)
        @post.user_id = current_user.id

        respond_to do |format|
            if @post.save
              format.html { redirect_to user_post_url(current_user, @post), notice: 'Post was successfully created.' }
            else
              format.html { render :new, status: :unprocessable_entity }
            end
          end
        
    end

    def post_params
        params.require(:post).permit(:title , :text , :comments_counter , :likes_counter)
    end


    def destroy
        @post = Post.find_by_id(params[:id])
        @post.destroy
        @post.update_user_posts_comment_counter
        redirect_to user_posts_path
        
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!

    def index
     @users=User.all()

    end

    def show
        @user=User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<div class='content'>
<section>
<p>Add New Comment</p>
<%= form_with model: @comment, url: user_post_comments_path, method: :post , local: true, class: "form-control" do |form|%>
<div>
    <%= form.label :text%>
    <%= form.text_area :text , placeholder: "Type comment" , rows: 20, required: true,  class: "form-post-text"%>
</div>
<div>
<%= form.submit "save" , class: "button"%>
</div>
<%end%>


</section>



</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>

      <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> 
  </body>
</html>

app/views/likes/new.html.erb
<div class='content'>
<%= form_with(model: @like , url: user_post_likes_path) do |form|%>
    <%= form.submit 'Add Like'%>
<%end%>
</div>

app/views/posts/index.html.erb
<h1>Posts</h1>
<div class='content'>
  <section class='user-info'>
        <img src=<%= @user.photo%>/>
        <h3 class='user'><%= @user.name%></h3>
        <h5>Number of post: <%= @user.post_counter || 0%></h5>
    </section>

 <% @post.each do |post|%>
          <section class='post'>
          <h2>Post#<%=post.id%></h2>
           <h3><%= link_to post.title , user_post_path(@user.id , post.id) %></h3>
            <%# <h4>Post#<%=post.id%></h4>
                <p>
                <%= post.text%>
                </p>
                <span><b>comments:</b> <%= post.comments_counter || 0%></span>
                <span><b>Likes:</b><%= post.likes_counter || 0%></span>
                <% if can? :destroy , post%>
                <button class='delete-btn'>
                <%= button_to 'Delete' , user_post_path(post.user_id , post.id) , method: :delete %>
                </button>
                <%end%>
           </section>
    <%end%>
     <%= button_to 'add new post' , new_user_post_url(id: @user.id) , method: :get%>
    <button class='btn'>
   
    Pegination</button>

</div>

app/views/posts/new.html.erb
<div class='content'>
<section class="container">
    <p class="post-title">Add New Post :</p>
    <%= form_with model: @post, url: user_posts_path, method: :post, local: true, class: "form-control" do |form| %>

        <%= form.hidden_field :comments_counter, value: 0 %>
        <%= form.hidden_field :likes_counter, value: 0 %>
        
        <div class="mb-3 mt-3">
            <%= form.label :title %>
            <%= form.text_field :title, placeholder: "Title", required: true, class: "form-post-title" %>        
        </div>

        <div>
            <%= form.label :text %>
            <%= form.text_area :text, placeholder: "Type your post here!", rows: 20, required: true,  class: "form-post-text" %>        
        </div>

        <div>
            <%= form.submit "Save", class: "button" %>
        </div>
    <% end %>
</section>

</div>

app/views/posts/show.html.erb
<div class='content'>
<section class='post-content'>
    <div class='post-header'>
      <h3>Post #<%= @user.id%> by <%= @user.name%></h3>
      <p><span>Comment: <%=@post.comments_counter || 0%></span>
      <span>Likes: <%=@post.likes_counter || 0%></span></p>
    </div>
    <h5><p><%= @post.title%> </p></h5>
    <p><%= @post.text%> </p>
</section>

 <section class='comment'>
      <h2>Comments</h2>
      <%@count=0%>
     <% @post.five_most_recent_comment.each do |comment|%>
      <div>

    <p><%=@count+=1%># <b>User:</b>  <%=comment.user.name%> ,<b>Comment:</b> <%=comment.text%>
      <% if can? :destroy , comment%>
                
                <%= button_to 'Delete Comment' , user_post_comment_path(comment.user_id , comment.post_id , comment.id) , method: 'delete' %>
               
      <%end%>
  </p> 
      </div>
    <%end%>
 </section>

 <div class='buttons'>
  <%= button_to 'Add new comment' , new_user_post_comment_path(@post.user_id , @post) , method: :get %>
   <%= button_to 'Add Like' , new_user_post_like_path(@post.user_id , @post) , method: :get %>
 </div>
</div>

app/views/users/index.html.erb
<h1>user List</h1>
<div class='content'>

<% @users.each do |user|%>
   <div class='item'>
   <img src=<%=user.photo%> alt='user'>
    <h3 class='user'><%= link_to user.name , user %></h3>
    <h5>Number of post: <%=user.post_counter%></h5>
   </div>
<%end%>

</div>

app/views/users/show.html.erb
<h1>User Details</h1>
<div class='content'>
    <section class='user-info'>
        <img src=<%= @user.photo%>/>
        <h3 class='user'><%= @user.name%></h3>
        <h5>Number of post: <%= @user.post_counter || 0%></h5>
    </section>
    <section class='bio'>
     <h4>bio</h4>
        <p>
        <%= @user.bio%>
        </p>
    </section>
    
    <% @user.recent_post.each do |post|%>
          <section class='post'>
            <h4><%=post.title%></h4>
                <p>
                <%= post.text%>
                </p>
           </section>
    <%end%>

    <button class='btn'>
        <%= link_to "See all post" , user_posts_path(@user)%>
    </button>
</div>